---
title: "Problem Set 3"
subtitle: "Due date: 25 September"
format: 
  html:
    self-contained: true
toc: true
editor: visual
execute: 
  warning: false
bibliography: references.bib
---

Please upload your completed assignment to the ELMs course site (under the assignments menu) and to your class Github repository. You need to upload both your Quarto document (with R code, as needed) and its rendered output (either as a PDF or HTML file).

**Total points: 30**

```{r}
dem_wealth_df <- readr::read_csv("http://svmiller.com/extdata/democracy-income-1950.csv") |> 
  dplyr::transmute(iso3c, country, gdp_per_cap = wbgdp2011est / wbpopest, democracy_score = xm_qudsest)
```

The `dem_wealth_df` data set (taken from the wonderful Dr Steven V Miller's [blog post](https://svmiller.com/blog/2023/09/democracy-income-correlation-analysis/)) will help us explore the relationship between a country's level of democracy and its citizens' wealth in 1950. It is a replication of [Lipset (1959)](https://www.cambridge.org/core/journals/american-political-science-review/article/abs/some-social-requisites-of-democracy-economic-development-and-political-legitimacy1/26559429359F42D3E9B8BC82CA65546A). Miller uses Xavier Marquez's [measure for democracy](https://www.cambridge.org/core/journals/political-analysis/article/democratic-compromise-a-latent-variable-analysis-of-ten-measures-of-regime-type/2A6B2BBA6F80367644F2C5007E1CFC29). This is a great (if complicated) measure. For this problem set, you only need to know that a country's level of democracy increases with its "democracy score".

## Question 1

### Part A

*Points: 2*

> Using the `dem_wealth_df` data frame loaded in above, produce a scatter plot of the variables `democracy_score` and `gdp_per_cap` (with `gdp_per_cap` as the dependent variable on the y-axis). Professionally format your graph.

### Part B

*Points: 3*

> Describe the scatter plot. Note suspected outliers if any exist (a visual inspection will suffice for this question).

## Question 2

*Points: 2*

> Calculate the correlation coefficient between `democracy_score` and `gdp_per_cap`. What does it tell you about the relationship between a country's level of democracy and its citizens' wealth?

## Question 3

I would like to know whether individuals with higher levels of education tend to pay greater levels of attention to politics than those with lower levels of education.

### Part A

*Points: 5*

> Using the `nes` data set in the `polisciols` R package, construct a cross-tab of the relationship between `attention_to_politics` and `education`. Focus only on those respondents who provided answers (filter out "Refused", "Don't know", and missing responses).

### Part B

*Points: 3*

> Describe the relationship between these two variables (if one exists).

## Question 4

*Points: 5*

I hypothesize that US voters who identify as being religious are less likely to support Federal government funding of scientific research. To test this, I run a survey of a representative sample of the US voting population. I ask respondents to indicate how often they attend religious ceremonies as a proxy measure of how strongly they identify as religious. They can answer: never, only for significant events, or regularly. Next, I ask respondents whether they think the Federal government's funding of scientific research is "too little", "about right", or "too much".

> Describe how you would construct a cross-tab to evaluate my hypothesis. Which responses (religious identification or support for Federal funding) would you compare within? Relatedly, which would you vary? Finally, what statistics would you use to make your comparisons?

## Question 5

Let's return to our original question of the relationship between democracy and individuals' wealth.

### Part A

*Points: 2*

> Create two new variables based on a country's level of democracy, and its citizens' wealth. For the democracy variable, split countries into three categories: `autocracy` if they score in the lowest third of democracy scores, `hybrid` if they score in the middle third, and `democracy` if they score in the highest third. Similarly, for the wealth variable, split countries into three categories: `low income` if they score in the lowest third of GDP per capita, `middle income` if they score in the middle third, and `high income` if they score in the highest third.

### Part B

*Points: 3*

> Create a cross-tab.

### Part C

*Points: 5*

> Describe the relationship between these variables.
