---
title: "Problem Set 2"
subtitle: "Due date: 23 September"
format: 
  html:
    self-contained: true
toc: true
editor: visual
execute: 
  echo: true
  warning: false
---

Please upload your completed assignment to the ELMs course site (under the assignments menu) and to your class Github repository. You need to upload both your Quarto document (with R code, as needed) and its rendered output (either as a PDF or HTML file).

**Total points: 25**

## Question 1

*Points: 10*

Suppose I want to examine the hypothesis that consuming political news coverage from cable network channels (e.g., CNN, MSNBC, Fox News, etc.) causes citizens to have less trust in government than if they were to consume it from mainstream print media (e.g., New York Times, Wall Street Journal, etc.). What is more, suppose that I believe that this effect is greatest among "young" citizens. Design the contours of an experiment to test this proposition (and be sure to sketch the key elements of the experimental design). Second, briefly describe any significant shortcomings that the experimental design might have.

## Question 2

*Points: 10*

Below are four hypothetical research designs to determine the effects of democratic governance on the funding of educational institutions. Briefly evaluate each sampling design in terms of its: (1) sampling variability; and, (2) sources of potential bias.

A.  A sample of educational funding levels for every country in Europe for each of the last 100 years.

B.  A sample of educational funding levels in five randomly picked countries drawn from the global population of countries for each of the last 10 years.

C.  A survey of educational administrators that yields responses that allow for a comparison of educational funding levels in Russia and the United States for the six-year period from 2010 to 2015.

D.  A sample of 75 randomly selected countries' educational funding levels for each of the past 25 years.

## Question 3

*Points: 5*

The COVID-19 pandemic wreaked havoc on the global economy. People became sick or died, supply chains snapped, and we all sheltered behind strict national borders or in our homes. We can see the effect of these changes when we look at how the growth of countries' Gross Domestic Product (GDP) changed between 2019 and the global pandemic's start in 2020.

::: callout-note
GDP is a popular measure of a country's annual economic output. Its annual growth tends to be approximately Normally distributed.
:::

```{r}
library(tidyverse)
library(wbstats)

gdp_growth_df <- wb_data("NY.GDP.MKTP.KD.ZG", 
                         start_date = 2019, 
                         end_date = 2020, 
                         return_wide = F)

ggplot(gdp_growth_df, aes(x = value, fill = factor(date))) + 
  geom_density(alpha = 0.75) + 
  theme_minimal() + 
  theme(plot.title = element_text(face = "bold"),
        plot.title.position = "plot") + 
  labs(title = "Countries' annual percentage growth rate of GDP in 2019 and 2020",
       x = "Annual growth in GDP (%)",
       y = "Density",
       fill = "Year",
       caption = "Source: World Bank")
```

### Part A

*Points: 2*

Describe the distribution of all countries' annual GDP growth rates in 2019 (found in the `gdp_growth_df` dataframe). Do the same for 2020. Include in those descriptions their five-number summaries.

### Part B

*Points: 2*

Calculate the mean and standard deviation of all countries' annual GDP growth rates in 2019. Do the same for 2020.

### Part C

*Points: 1*

Compare the mean and standard deviation of GDP growth rates in 2019 with those in 2020. What, generally, happened to each country's economy? Do not use the words or phrases "mean" or "standard deviation" in your answer.
